### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by gokulsukumar03** [mgsx-dev/gdx-gltf#1]
HI,
   Facing issue in both (.glb) and (gltf) file.  

2019-02-28 15:33:44.156 31927-32093/net.mgsx.gltf.demo E/AndroidRuntime: FATAL EXCEPTION: GLThread 102412
    Process: net.mgsx.gltf.demo, PID: 31927
    com.badlogic.gdx.utils.GdxRuntimeException: Fragment shader:
    WARNING: 0:3: extension 'GL_EXT_shader_texture_lod' is not supported
    ERROR: 0:313: 'textureCubeLodEXT' : no matching overloaded function found 
    ERROR: 0:313: 'SRGBtoLINEAR' : no matching overloaded function found 
    ERROR: 0:313: 'rgb' :  field selection requires structure, vector, or matrix on left hand side 
    ERROR: 0:313: '=' :  cannot convert from 'const float' to '3-component vector of float'
    ERROR: 4 compilation errors.  No code generated.
    
    
        at com.badlogic.gdx.graphics.g3d.shaders.BaseShader.init(BaseShader.java:167)
        at net.mgsx.gltf.scene3d.shaders.PBRShader.init(PBRShader.java:265)
        at com.badlogic.gdx.graphics.g3d.shaders.DefaultShader.init(DefaultShader.java:595)
        at com.badlogic.gdx.graphics.g3d.utils.BaseShaderProvider.getShader(BaseShaderProvider.java:35)
        at com.badlogic.gdx.graphics.g3d.ModelBatch.render(ModelBatch.java:263)
        at net.mgsx.gltf.scene3d.scene.SceneManager.render(SceneManager.java:85)
        at net.mgsx.gltf.demo.GLTFDemo.render(GLTFDemo.java:530)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:495)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
2019-02-28 15:33:48.205 31927-31927/net.mgsx.gltf.demo E/AndroidGraphics: waiting for pause synchronization took too long; assuming deadlock and killing

**Comment by mgsx-dev** [comment]
Ah thanks for the information, I didn't tested on android yet. I'll try to fix it as soon as i can.

**Comment by mgsx-dev** [comment]
I quickly tested on a lowend device (Android 4.2.2) and it doesn't crash.

What's your configuration (Android version, device, etc) ?

**Comment by mgsx-dev** [comment]
@gokulsukumar03 i think i fixed the issue, i'm not able to test it since my android device has 
shader_texture_lod extension supported. Could you test it with the last commit and tell me if it works. If not please tell me what's the error.

**Comment by Josid88** [comment]
Hi, I left you a comment on the app last week, great work, but it didn't work on my Android device it is a Moto G4. Do you need mor information or something else?

**Comment by mgsx-dev** [comment]
@Josid88 Hi, sorry i didn't get notification about your comment on PlayStore. I'm actually waiting for @gokulsukumar03 feedback about my fix before publishing Android update. Maybe i'll publish anyway soon.

Best information is error stacktrace from logcat. If you can provide it here, it'd be great!

**Comment by Josid88** [comment]
Sorry for not replying any sooner, here is the log, I think is the same error from @gokulsukumar03 

`
--------- beginning of crash
04-03 22:43:02.744 31008-31031/? E/AndroidRuntime: FATAL EXCEPTION: GLThread 1808
    Process: net.mgsx.gltf.demo, PID: 31008
    com.badlogic.gdx.utils.GdxRuntimeException: Fragment shader:
    ERROR: 0:318: 'textureCubeLod' : no matching overloaded function found 
    ERROR: 0:318: 'SRGBtoLINEAR' : no matching overloaded function found 
    ERROR: 0:318: 'rgb' :  field selection requires structure, vector, or matrix on left hand side 
    ERROR: 0:318: '=' :  cannot convert from 'const float' to '3-component vector of float'
    ERROR: 4 compilation errors.  No code generated.
    
    
        at com.badlogic.gdx.graphics.g3d.shaders.BaseShader.init(BaseShader.java:167)
        at net.mgsx.gltf.scene3d.shaders.PBRShader.init(PBRShader.java:265)
        at com.badlogic.gdx.graphics.g3d.shaders.DefaultShader.init(DefaultShader.java:595)
        at com.badlogic.gdx.graphics.g3d.utils.BaseShaderProvider.getShader(BaseShaderProvider.java:35)
        at com.badlogic.gdx.graphics.g3d.ModelBatch.render(ModelBatch.java:263)
        at net.mgsx.gltf.scene3d.scene.SceneManager.render(SceneManager.java:85)
        at net.mgsx.gltf.demo.GLTFDemo.render(GLTFDemo.java:519)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:495)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1553)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253)
`

**Comment by mgsx-dev** [comment]
@Josid88 Thanks, i published a fix. Android update should be available soon. Unfortunately i don't have GLES3 device to test it, thanks to tell me if it fix your issue.

**Comment by Josid88** [comment]
@mgsx-dev Now is throwing a different error

Increasing code cache capacity to 256KB
04-05 10:13:43.154 13553-13570/? I/Adreno: ERROR: Invalid #version
04-05 10:13:43.156 13553-13570/? I/Adreno: ERROR: Invalid #version
04-05 10:13:43.161 13553-13570/? I/Shader compilation: Vertex shader
    ERROR: Invalid #version
    Fragment shader:
    ERROR: Invalid #version
04-05 10:13:43.204 13553-13553/? I/Choreographer: Skipped 163 frames!  The application may be doing too much work on its main thread.
    
    --------- beginning of crash
04-05 10:13:43.210 13553-13570/? E/AndroidRuntime: FATAL EXCEPTION: GLThread 556
    Process: net.mgsx.gltf.demo, PID: 13553
    com.badlogic.gdx.utils.GdxRuntimeException: Vertex shader
    ERROR: Invalid #version
    Fragment shader:
    ERROR: Invalid #version
    
        at com.badlogic.gdx.graphics.g3d.shaders.BaseShader.init(BaseShader.java:167)
        at net.mgsx.gltf.scene3d.shaders.PBRShader.init(PBRShader.java:265)
        at com.badlogic.gdx.graphics.g3d.shaders.DefaultShader.init(DefaultShader.java:595)
        at com.badlogic.gdx.graphics.g3d.utils.BaseShaderProvider.getShader(BaseShaderProvider.java:35)
        at com.badlogic.gdx.graphics.g3d.ModelBatch.render(ModelBatch.java:263)
        at net.mgsx.gltf.scene3d.scene.SceneManager.render(SceneManager.java:85)
        at net.mgsx.gltf.demo.GLTFDemo.render(GLTFDemo.java:519)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:495)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1553)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253)
04-05 10:13:43.218 1589-4854/? W/ActivityManager:   Force finishing activity net.mgsx.gltf.demo/.AndroidLauncher
04-05 10:13:43.248 1589-4801/? W/InputMethodManagerService: Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@4f6db46 (uid=10145 pid=13553)
04-05 10:13:43.252 1589-3738/? E/ActivityManager: Sending non-protected broadcast com.motorola.motocare.INTENT_TRIGGER from system 3976:com.motorola.process.system/1000 pkg com.motorola.motgeofencesvc
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18226)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18826)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:512)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2906)
        at android.os.Binder.execTransact(Binder.java:565)

**Comment by mgsx-dev** [comment]
@Josid88 really sorry about that, i just published a fix, i hope it'll be ok now.

Thanks again for your help, i appreciate it!

**Comment by Josid88** [comment]
I answered in android app on weekend. Is working perfect, In my phone controls are very small and hard to click on them, but it's OK.

**Comment by mgsx-dev** [comment]
@Josid88 thanks god :D and thanks to you!

@gokulsukumar03 could you please test again to confirm it fixes the issue for you as well?

**Comment by gokulsukumar03** [comment]
> @Josid88 thanks god :D and thanks to you!
> 
> @gokulsukumar03 could you please test again to confirm it fixes the issue for you as well?

sorry for the late response. I will do it.
