### ISSUE TITLE
Skybox fragment shader error in 2.2.1 on Android

### ISSUE THREAD

**Issue by yahel-ck** [mgsx-dev/gdx-gltf#130]
Hey :)

I'm trying to upgrade my project to use gdx-gltf version 2.2.1 (currently using 2.1.0) and I'm getting a compilation error in the fragment shader of the Skybox:
```
com.badlogic.gdx.utils.GdxRuntimeException: Fragment shader:
    ERROR: 0:1: '' :  version '430' is not supported
    ERROR: 0:2: '' :  #version required and missing.
        at com.badlogic.gdx.graphics.g3d.shaders.BaseShader.init(BaseShader.java:169)
        at com.badlogic.gdx.graphics.g3d.shaders.DefaultShader.init(DefaultShader.java:624)
        at net.mgsx.gltf.scene3d.scene.SceneSkybox$SkyboxShader.init(SceneSkybox.java:191)
        at com.badlogic.gdx.graphics.g3d.utils.BaseShaderProvider.getShader(BaseShaderProvider.java:36)
        at net.mgsx.gltf.scene3d.scene.SceneSkybox.getRenderables(SceneSkybox.java:247)
...
```
I got this error when running on an Android emulator (Pixel 5 API 32), but I got no error when running on a real Pixel 8 device.

I was using the basic constructor `SceneSkybox(envCubemap)` to create it, and I also tried `SceneSkybox(envCubemap, SRGB.NONE, null, true)` because I noticed the the new code adds `#version` if lod is enabled, and it did run on the Pixel 5 emulator, but this time I got an exception on my Pixel 8 device:
```
com.badlogic.gdx.utils.GdxRuntimeException: L0001 Shader languages do not match.
        at com.badlogic.gdx.graphics.g3d.shaders.BaseShader.init(BaseShader.java:169)
        at com.badlogic.gdx.graphics.g3d.shaders.DefaultShader.init(DefaultShader.java:624)
        at net.mgsx.gltf.scene3d.scene.SceneSkybox$SkyboxShader.init(SceneSkybox.java:191)
        at com.badlogic.gdx.graphics.g3d.utils.BaseShaderProvider.getShader(BaseShaderProvider.java:36)
        at net.mgsx.gltf.scene3d.scene.SceneSkybox.getRenderables(SceneSkybox.java:247)
        at com.badlogic.gdx.graphics.g3d.ModelBatch.render(ModelBatch.java:239)
```

I would appreciate some help to fix this so I can run this properly on all devices.
Thanks :)

**Comment by mgsx-dev** [comment]
Hi, for the first error (version '430' is not supported) is a bit weird because the library never set version 430 anywhere. So either you set it via ShaderProgram.prependFragmentCode somewhere or the Android emulator inject it for no reason and it can't anything about it.

For the second error, as stated in the documentation, enabling lods require GLES 3.0+ so you need to configure your Android launcher to use the right GLES version : (config.useGL30 = true).

Feel free to reopen if you think i can change something.
