### ISSUE TITLE
Issue with GLTFQuickStartExample android 

### ISSUE THREAD

**Issue by kulnaman** [mgsx-dev/gdx-gltf#33]
Hi,
Going through the library I have used the GLTFQuickStartExample class as a example to load a simple gltf model. But running the app results in a crash with error

`2021-01-16 16:14:13.402 30170-30205/com.example.maxst3demo E/AndroidRuntime: FATAL EXCEPTION: GLThread 3491
    Process: com.example.maxst3demo, PID: 30170
    java.lang.NullPointerException: Attempt to invoke interface method 'com.badlogic.gdx.files.FileHandle com.badlogic.gdx.Files.internal(java.lang.String)' on a null object reference
        at com.example.maxst3demo.imageTracker.GLTFQuickStartExample.create(GLTFQuickStartExample.java:48)
        at com.example.maxst3demo.imageTracker.ImageTrackerRenderer.addGM(ImageTrackerRenderer.java:107)
        at com.example.maxst3demo.imageTracker.ImageTrackerActivity.load3DModel(ImageTrackerActivity.java:97)
        at com.example.maxst3demo.imageTracker.ImageTrackerActivity.lambda$cZoV0UmnlP2C_Kv2pF17Z95xcBc(Unknown Source:0)
        at com.example.maxst3demo.imageTracker.-$$Lambda$ImageTrackerActivity$cZoV0UmnlP2C_Kv2pF17Z95xcBc.run(Unknown Source:2)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1502)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)`

Do i have to call some type of init method before calling the ` sceneAsset=gltfLoader.load(Gdx.files.internal("models/BoomBox/glTF/BoomBox.gltf"));`
load method ?

**Comment by mgsx-dev** [comment]
yes, libGDX need to be initialized before calling any Gdx class method.
