### ISSUE TITLE
Crash when use AndroidStudio open and run

### ISSUE THREAD

**Issue by peerless2012** [mgsx-dev/gdx-gltf#49]
```
java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-libart.jar)
at net.mgsx.gltf.loaders.shared.data.DataResolver.getBufferByte(DataResolver.java:84)
        at net.mgsx.gltf.loaders.shared.data.DataResolver.getBufferShort(DataResolver.java:78)
        at net.mgsx.gltf.loaders.shared.geometry.MeshLoader.loadIndices(MeshLoader.java:353)
        at net.mgsx.gltf.loaders.shared.geometry.MeshLoader.load(MeshLoader.java:54)
        at net.mgsx.gltf.loaders.shared.GLTFLoaderBase.getNode(GLTFLoaderBase.java:277)
        at net.mgsx.gltf.loaders.shared.GLTFLoaderBase.loadScene(GLTFLoaderBase.java:199)
        at net.mgsx.gltf.loaders.shared.GLTFLoaderBase.loadScenes(GLTFLoaderBase.java:178)
        at net.mgsx.gltf.loaders.shared.GLTFLoaderBase.load(GLTFLoaderBase.java:126)
        at net.mgsx.gltf.loaders.gltf.GLTFLoader.load(GLTFLoader.java:16)
        at net.mgsx.gltf.loaders.gltf.GLTFLoader.load(GLTFLoader.java:11)
        at net.mgsx.gltf.examples.GLTFQuickStartExample.create(GLTFQuickStartExample.java:41)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:278)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

**Comment by mgsx-dev** [comment]
sorry for the delay. This issue is due to a kind of mismatch between JDK and Android. A controversial workaround has been added in libGDX (see https://github.com/libgdx/libgdx/pull/6331) but apparently there are some cleaner way to fix it in your project, see this article : https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/.

Another workaround is to use JDK 8 when compiling for Android.
