### ISSUE TITLE
Procedural models generation causes crashes on Android.

### ISSUE THREAD

**Issue by dmoklyakov** [mgsx-dev/gdx-gltf#62]
I compiled code from [this tutorial](https://github.com/mgsx-dev/gdx-gltf/blob/master/gltf/test/net/mgsx/gltf/procedural/ProceduralExamples.java) and got the following errors:

On Pixel 6 Pro (Android 12):
```2022-01-06 23:08:12.199 22161-22204/com.mygdx.game E/AndroidRuntime: FATAL EXCEPTION: GLThread 57
    Process: com.mygdx.game, PID: 22161
    com.badlogic.gdx.utils.GdxRuntimeException: Shader compilation failed:
    Fragment shader:
    0:196: P0008: Error parsing constant expression, unknown identifier 'numDirectionalLights'
    0:196: P0001: Error parsing constant expression
    0:206: P0008: Error parsing constant expression, unknown identifier 'numPointLights'
    0:206: P0001: Error parsing constant expression
    0:215: P0008: Error parsing constant expression, unknown identifier 'numSpotLights'
    0:215: P0001: Error parsing constant expression
    0:202: L0002: Undeclared variable 'numDirectionalLights'
        at net.mgsx.gltf.scene3d.shaders.PBRShaderProvider.checkShaderCompilation(PBRShaderProvider.java:357)
        at net.mgsx.gltf.scene3d.shaders.PBRShaderProvider.createShader(PBRShaderProvider.java:327)
        at com.badlogic.gdx.graphics.g3d.utils.BaseShaderProvider.getShader(BaseShaderProvider.java:34)
        at com.badlogic.gdx.graphics.g3d.ModelBatch.render(ModelBatch.java:261)
        at com.badlogic.gdx.graphics.g3d.ModelBatch.render(ModelBatch.java:272)
        at net.mgsx.gltf.scene3d.scene.SceneManager.renderColors(SceneManager.java:228)
        at net.mgsx.gltf.scene3d.scene.SceneManager.render(SceneManager.java:184)
        at com.mygdx.game.ProceduralExamples.render(ProceduralExamples.kt:212)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:471)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
2022-01-06 23:08:16.222 22161-22161/com.mygdx.game E/AndroidGraphics: waiting for pause synchronization took too long; assuming deadlock and killing
```

on Asus ZenFone 7 Pro (Android 10):
```2022-01-06 23:14:22.419 8099-8126/com.mygdx.game E/AndroidRuntime: FATAL EXCEPTION: GLThread 111211
    Process: com.mygdx.game, PID: 8099
    com.badlogic.gdx.utils.GdxRuntimeException: Shader compilation failed:
    Fragment shader:
    ERROR: 0:196: '' :     GLSL compile error:  unresolved identifier
    ERROR: 0:196: '' :     GLSL compile error:  unexpected tokens following an #if or #elif.
    ERROR: 0:202: 'numDirectionalLights' : undeclared identifier 
    ERROR: 0:202: 'numDirectionalLights' : Only consts can be used in a global initializer 
    ERROR: 0:202: '' : constant expression required 
    ERROR: 0:202: '' : array size must be a constant expression 
    ERROR: 0:206: '' :     GLSL compile error:  unresolved identifier
    ERROR: 0:206: '' :     GLSL compile error:  unexpected tokens following an #if or #elif.
    ERROR: 0:212: 'numPointLights' : undeclared identifier 
    ERROR: 0:212: 'numPointLights' : Only consts can be used in a global initializer 
    ERROR: 0:212: '' : constant expression required 
    ERROR: 0:212: '' : array size must be a constant expression 
    ERROR: 0:215: '' :     GLSL compile error:  unresolved identifier
    ERROR: 0:215: '' :     GLSL compile error:  unexpected tokens following an #if or #elif.
    ERROR: 0:224: 'numSpotLights' : undeclared identifier 
    ERROR: 0:224: 'numSpotLights' : Only consts can be used in a global initializer 
    ERROR: 0:224: '' : constant expression required 
    ERROR: 0:224: '' : array size must be a constant expression 
    ERROR: 18 compilation errors.  No code generated.
    
    
        at net.mgsx.gltf.scene3d.shaders.PBRShaderProvider.checkShaderCompilation(PBRShaderProvider.java:357)
        at net.mgsx.gltf.scene3d.shaders.PBRShaderProvider.createShader(PBRShaderProvider.java:327)
        at com.badlogic.gdx.graphics.g3d.utils.BaseShaderProvider.getShader(BaseShaderProvider.java:34)
        at com.badlogic.gdx.graphics.g3d.ModelBatch.render(ModelBatch.java:261)
        at com.badlogic.gdx.graphics.g3d.ModelBatch.render(ModelBatch.java:272)
        at net.mgsx.gltf.scene3d.scene.SceneManager.renderColors(SceneManager.java:228)
        at net.mgsx.gltf.scene3d.scene.SceneManager.render(SceneManager.java:184)
        at com.mygdx.game.ProceduralExamples.render(ProceduralExamples.kt:212)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:471)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
2022-01-06 23:14:26.431 8099-8099/com.mygdx.game E/AndroidGraphics: waiting for pause synchronization took too long; assuming deadlock and killing
```

**Comment by mgsx-dev** [comment]
@dmoklyakov which gdx-gltf version are you using? and could you please post the code you're running.

i'm wondering if you can run some libgdx 3D code on those devices without any errors, because it seems to crash at some basic expressions like `#if numDirectionalLights > 0` which are present in default libgdx shaders too.

It would be easier if we could talk about it on the libgdx Discord in order to understand what's going on.

**Comment by dmoklyakov** [comment]
@mgsx-dev I'm using `2.0.0-rc.1` version.

I can run a project using models loaded from .glb files with GLTF library, and I also can run a project without GLTF library with procedurally generated models using only pure LibGDX.

I made a minimal project so you can reproduce this error:
[MyGdxGame2.zip](https://github.com/mgsx-dev/gdx-gltf/files/7824998/MyGdxGame2.zip).

In case you need more operative feedback from me, I have sent you a friend request at Discord.

**Comment by dmoklyakov** [comment]
Discussed in Discord: fix should be available soon.
