### ISSUE TITLE
Vertex shader do not fit in 256 vectors

### ISSUE THREAD

**Issue by RoberMS** [mgsx-dev/gdx-gltf#7]
Good afternoon, I get the following error:

com.badlogic.gdx.utils.GdxRuntimeException: Shader compilation failed:
--From Vertex Shader:
    Error: uniform variables in vertex shader do not fit in 256 vectors.
--From Fragment Shader:
    Error: uniform variables in vertex shader do not fit in 256 vectors.

at net.mgsx.gltf.scene3d.shaders.PBRShaderProvider.createShader(PBRShaderProvider.java:295)
at com.badlogic.gdx.graphics.g3d.utils.BaseShaderProvider.getShader(BaseShaderProvider.java:34)
at com.badlogic.gdx.graphics.g3d.ModelBatch.render(ModelBatch.java:262)
at net.mgsx.gltf.scene3d.scene.SceneManager.renderColors(SceneManager.java:149)
at net.mgsx.gltf.scene3d.scene.SceneManager.render(SceneManager.java:116)
at com.proof.gltf.GLTFLoader.render(GLTFLoader.java:352)
at com.badlogic.gdx.backends.android.AndroidGraphicsLiveWallpaper.onDrawFrame(AndroidGraphicsLiveWallpaper.java:220)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

**Comment by mgsx-dev** [comment]
Hi, could you please link your GLTF files (in a zip) and tell me how many lights do you have?

**Comment by RoberMS** [comment]
I attached the glTF file. the error is shown in mid / low range mobiles, for example in lg v30 works perfect.
[glTF.zip](https://github.com/mgsx-dev/gdx-gltf/files/3928276/glTF.zip)

**Comment by mgsx-dev** [comment]
108 bones for a single model is way too high for video games. Typically (because of GPU limitations) you don't go over 30 bones for mobile and 60 bones for desktop.

Maybe you could optimize your model by removing some bones or simplify armature. Alternatively,  you could split it in several armatures (which would be more complicated to handle in game).

**Comment by mgsx-dev** [comment]
as you can see [here](https://bocoup.com/blog/counting-uniforms-in-webgl) desktop limit is typically 1024 uniforms and 256 for mobile (lowend device i guess).
Since a bone (mat4) takes 4 uniforms,  you have a hard limit on desktop : 256 bones, and on mobile : 64 bones.
Note that few other uniforms are needed for the shaders so i wouldn't go over 50 bones. It depends on how many lights you have as well.
