### ISSUE TITLE
Error during load model what's texture name contains space

### ISSUE THREAD

**Issue by Dgzt** [mgsx-dev/gdx-gltf#81]
The GLTFLoader throws exception if I want to load a model what's texture name contains space.

![image](https://user-images.githubusercontent.com/1684274/197180790-30323ff9-a423-4239-b6c8-4fed8caf6e71.png)

The code:

`SceneAsset sceneAsset = new GLTFLoader().load(Gdx.files.internal("house_wrong.gltf"));`

Exception:

`Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: Plane%20Base%20Color.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:190)
	at net.mgsx.gltf.loaders.gltf.SeparatedDataFileResolver.load(SeparatedDataFileResolver.java:93)
	at net.mgsx.gltf.loaders.shared.texture.ImageResolver.load(ImageResolver.java:25)
	at net.mgsx.gltf.loaders.shared.GLTFLoaderBase.load(GLTFLoaderBase.java:114)
	at net.mgsx.gltf.loaders.gltf.GLTFLoader.load(GLTFLoader.java:16)
	at net.mgsx.gltf.loaders.gltf.GLTFLoader.load(GLTFLoader.java:11)
	at com.mygdx.game.MyGdxGame.create(MyGdxGame.java:19)
`

I used _2.0.0-rc.1_ version.

**Comment by Dgzt** [comment]
I've tested with master-SNAPSHOT version too but I get this exception.

**Comment by mgsx-dev** [comment]
Yep, that was something i noticed recently, it should work now.
